openapi: "3.0.3"

info:
  title: "holos: アカウントAPI"
  version: ""

servers:
  - url: "http://localhost:8001"
    description: "localhost"
  - url: "http://account-api:8000"
    description: "docker compose service"

paths:
  /health:
    get:
      summary: "ヘルスチェック"
      tags:
        - "health"
      responses:
        204:
          $ref: "#/components/responses/no_content"
  /accounts:
    post:
      summary: "アカウント作成"
      tags:
        - "accounts"
      requestBody:
        $ref: "#/components/requestBodies/create_account"
      responses:
        201:
          $ref: "#/components/responses/create_account"
        400:
          $ref: "#/components/responses/bad_request"
        409:
          $ref: "#/components/responses/duplicate"
        422:
          $ref: "#/components/responses/invalid_input"
        500:
          $ref: "#/components/responses/internal_server_error"
    delete:
      summary: "アカウント削除"
      tags:
        - "accounts"
      security:
        - sessionAuth: []
      parameters:
        - in: "header"
          name: "Authorization"
          schema:
            type: "string"
          required: true
          description: "セッショントークン"
          example: "Session 1Ty1HKTPKTt8xEi-_3HTbWf2SCHOdqOS"
      requestBody:
        $ref: "#/components/requestBodies/delete_account"
      responses:
        204:
          $ref: "#/components/responses/no_content"
        400:
          $ref: "#/components/responses/bad_request"
        401:
          $ref: "#/components/responses/unauthenticated"
        500:
          $ref: "#/components/responses/internal_server_error"
  /accounts/name:
    patch:
      summary: "アカウント名更新"
      tags:
        - "accounts"
      security:
        - sessionAuth: []
      parameters:
        - in: "header"
          name: "Authorization"
          schema:
            type: "string"
          required: true
          description: "セッショントークン"
          example: "Session 1Ty1HKTPKTt8xEi-_3HTbWf2SCHOdqOS"
      requestBody:
        $ref: "#/components/requestBodies/update_account_name"
      responses:
        200:
          $ref: "#/components/responses/update_account_name"
        400:
          $ref: "#/components/responses/bad_request"
        401:
          $ref: "#/components/responses/unauthenticated"
        409:
          $ref: "#/components/responses/duplicate"
        422:
          $ref: "#/components/responses/invalid_input"
        500:
          $ref: "#/components/responses/internal_server_error"
  /accounts/password:
    patch:
      summary: "パスワード更新"
      tags:
        - "accounts"
      security:
        - sessionAuth: []
      parameters:
        - in: "header"
          name: "Authorization"
          schema:
            type: "string"
          required: true
          description: "セッショントークン"
          example: "Session 1Ty1HKTPKTt8xEi-_3HTbWf2SCHOdqOS"
      requestBody:
        $ref: "#/components/requestBodies/update_account_password"
      responses:
        200:
          $ref: "#/components/responses/update_account_password"
        400:
          $ref: "#/components/responses/bad_request"
        401:
          $ref: "#/components/responses/unauthenticated"
        422:
          $ref: "#/components/responses/invalid_input"
        500:
          $ref: "#/components/responses/internal_server_error"
  /sessions:
    post:
      summary: "セッション作成"
      tags:
        - "session"
      requestBody:
        $ref: "#/components/requestBodies/create_session"
      responses:
        201:
          $ref: "#/components/responses/create_session"
        400:
          $ref: "#/components/responses/bad_request"
        401:
          $ref: "#/components/responses/unauthenticated"
        500:
          $ref: "#/components/responses/internal_server_error"
    delete:
      summary: "セッション削除"
      tags:
        - "session"
      security:
        - sessionAuth: []
      parameters:
        - in: "header"
          name: "Authorization"
          schema:
            type: "string"
          required: true
          description: "セッショントークン"
          example: "Session 1Ty1HKTPKTt8xEi-_3HTbWf2SCHOdqOS"
      responses:
        204:
          $ref: "#/components/responses/no_content"
        401:
          $ref: "#/components/responses/unauthenticated"
        500:
          $ref: "#/components/responses/internal_server_error"
  /sessions/verify:
    get:
      summary: "セッション検証"
      tags:
        - "session"
      security:
        - sessionAuth: []
      parameters:
        - in: "header"
          name: "Authorization"
          schema:
            type: "string"
          required: true
          description: "セッショントークン"
          example: "Session 1Ty1HKTPKTt8xEi-_3HTbWf2SCHOdqOS"
      responses:
        200:
          $ref: "#/components/responses/verified_session"
        401:
          $ref: "#/components/responses/unauthenticated"
        500:
          $ref: "#/components/responses/internal_server_error"

components:
  securitySchemes:
    sessionAuth:
      type: http
      scheme: Session

  schemas:
    account:
      type: "object"
      properties:
        id:
          type: "string"
          example: "397bde64-8042-4e38-bca0-a4ba9f4f0e5f"
          readOnly: true
        name:
          type: "string"
          example: "develop"
        password:
          type: "string"
          example: "b8U*|5DTEl7N"
          writeOnly: true
        confirm_password:
          type: "string"
          example: "b8U*|5DTEl7N"
          writeOnly: true
      required:
        - "id"
        - "name"
        - "password"
        - "confirm_password"
    credential:
      type: "object"
      properties:
        account_name:
          type: "string"
          example: "develop"
          writeOnly: true
        password:
          type: "string"
          example: "b8U*|5DTEl7N"
          writeOnly: true
    session:
      type: "object"
      properties:
        token:
          type: "string"
          example: "1Ty1HKTPKTt8xEi-_3HTbWf2SCHOdqOS"
          readOnly: true

  requestBodies:
    create_account:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/account"
    update_account_name:
      required: true
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/account"
              - type: "object"
                properties:
                  confirm_password:
                    readOnly: true
    update_account_password:
      required: true
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/account"
              - type: "object"
                properties:
                  name:
                    readOnly: true
                  new_password:
                    type: "string"
                    example: "G922x£4a2W:2"
    delete_account:
      required: true
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/account"
              - type: "object"
                properties:
                  name:
                    readOnly: true
                  confirm_password:
                    readOnly: true
    create_session:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/credential"

  responses:
    create_account:
      description: "Success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/account"
              - type: "object"
                properties:
                  id:
                    writeOnly: true
    update_account_name:
      description: "Success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/account"
              - type: "object"
                properties:
                  id:
                    writeOnly: true
    update_account_password:
      description: "Success"
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/account"
              - type: "object"
                properties:
                  id:
                    writeOnly: true
    create_session:
      description: "Success"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/session"
    verified_session:
      description: "Success"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/account"
    no_content:
      description: "Success"
    bad_request:
      description: "Bad Request"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              error:
                type: "object"
                properties:
                  code:
                    type: "string"
                    example: "BAD_REQUEST"
                  message:
                    type: "string"
                    example: "bad request"
    unauthenticated:
      description: "Unauthenticated"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              error:
                type: "object"
                properties:
                  code:
                    type: "string"
                    example: "UNAUTHENTICATED"
                  message:
                    type: "string"
                    example: "unauthenticated"
    duplicate:
      description: "Duplicate"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              error:
                type: "object"
                properties:
                  code:
                    type: "string"
                    example: "DUPLICATE"
                  message:
                    type: "string"
                    example: "duplicate"
    invalid_input:
      description: "Invalid Input"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              error:
                type: "object"
                properties:
                  code:
                    type: "string"
                    example: "INVALID_INPUT"
                  message:
                    type: "string"
                    example: "invalid input"
    internal_server_error:
      description: "Internal Server Error"
      content:
        application/json:
          schema:
            type: "object"
            properties:
              error:
                type: "object"
                properties:
                  code:
                    type: "string"
                    example: "INTERNAL_SERVER_ERROR"
                  message:
                    type: "string"
                    example: "internal server error"
